{
 "title": "P2P",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM peer_infos"
   }
  ]
 },
 "panels": [
  {
   "title": "Peer connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SELECT timestamp as time,COUNT(node) FROM peer_infos WHERE is_outbound = TRUE GROUP BY timestamp ORDER BY timestamp DESC",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(id) AS \"outbound\"\nFROM peer_infos\nWHERE\n  $__timeFilter(\"timestamp\")\n  and is_outbound = TRUE\n  and node = '$node'\nGROUP BY timestamp\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(id) AS \"inbound\"\nFROM peer_infos\nWHERE\n  $__timeFilter(\"timestamp\")\n  and is_outbound IS NULL\n  and node = '$node'\nGROUP BY timestamp\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current Peers",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  moniker,listen_addr as \"Address\",is_outbound,version\nFROM peer_infos\nWHERE\n  timestamp = (select max(timestamp) from peer_infos as f where f.node = '$node')\n  and node = '$node'\nGROUP BY is_outbound,listen_addr,version,moniker"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(id) AS \"outbound\"\nFROM peer_infos\nWHERE\n  $__timeFilter(\"timestamp\")\n  and is_outbound = TRUE\n  and node = '$node'\nGROUP BY timestamp\nORDER BY 1",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  listen_addr,\n  (recv_data->>'CurRate')::int as recv,\n  (send_data->>'CurRate')::int as send\nFROM peer_infos\nWHERE\n  $__timeFilter(\"timestamp\")\n  and node = '$node'\nGROUP BY timestamp,recv_data,send_data,listen_addr\nORDER BY 1"
    }
   ]
  }
 ]
}